"""
Stock universe lists for NASDAQ 100, S&P 100, and NIFTY 100
"""

NASDAQ_100 = [
    ("AAPL", "Apple Inc."), ("MSFT", "Microsoft Corp."), ("NVDA", "NVIDIA Corp."),
    ("AMZN", "Amazon.com Inc."), ("META", "Meta Platforms Inc."), ("TSLA", "Tesla Inc."),
    ("GOOGL", "Alphabet Inc. Class A"), ("GOOG", "Alphabet Inc. Class C"),
    ("AVGO", "Broadcom Inc."), ("COST", "Costco Wholesale Corp."),
    ("NFLX", "Netflix Inc."), ("ASML", "ASML Holding NV"), ("TMUS", "T-Mobile US Inc."),
    ("CSCO", "Cisco Systems Inc."), ("AMD", "Advanced Micro Devices Inc."),
    ("PEP", "PepsiCo Inc."), ("ADBE", "Adobe Inc."), ("INTU", "Intuit Inc."),
    ("TXN", "Texas Instruments Inc."), ("QCOM", "Qualcomm Inc."),
    ("AMGN", "Amgen Inc."), ("HON", "Honeywell International Inc."),
    ("ISRG", "Intuitive Surgical Inc."), ("AMAT", "Applied Materials Inc."),
    ("SBUX", "Starbucks Corp."), ("VRTX", "Vertex Pharmaceuticals Inc."),
    ("GILD", "Gilead Sciences Inc."), ("PANW", "Palo Alto Networks Inc."),
    ("ADI", "Analog Devices Inc."), ("REGN", "Regeneron Pharmaceuticals Inc."),
    ("LRCX", "Lam Research Corp."), ("KLAC", "KLA Corp."),
    ("SNPS", "Synopsys Inc."), ("MU", "Micron Technology Inc."),
    ("CDNS", "Cadence Design Systems Inc."), ("CSX", "CSX Corp."),
    ("ORLY", "O'Reilly Automotive Inc."), ("MELI", "MercadoLibre Inc."),
    ("MDLZ", "Mondelez International Inc."), ("ABNB", "Airbnb Inc."),
    ("MAR", "Marriott International Inc."), ("FTNT", "Fortinet Inc."),
    ("KDP", "Keurig Dr Pepper Inc."), ("CPRT", "Copart Inc."),
    ("NXPI", "NXP Semiconductors NV"), ("CTAS", "Cintas Corp."),
    ("DXCM", "DexCom Inc."), ("PAYX", "Paychex Inc."),
    ("BIIB", "Biogen Inc."), ("WDAY", "Workday Inc."),
    ("MNST", "Monster Beverage Corp."), ("CRWD", "CrowdStrike Holdings Inc."),
    ("FAST", "Fastenal Co."), ("ODFL", "Old Dominion Freight Line Inc."),
    ("PCAR", "PACCAR Inc."), ("ADP", "Automatic Data Processing Inc."),
    ("IDXX", "IDEXX Laboratories Inc."), ("ROST", "Ross Stores Inc."),
    ("BKR", "Baker Hughes Co."), ("MCHP", "Microchip Technology Inc."),
    ("ZS", "Zscaler Inc."), ("TEAM", "Atlassian Corp."),
    ("DLTR", "Dollar Tree Inc."), ("ON", "ON Semiconductor Corp."),
    ("VRSK", "Verisk Analytics Inc."), ("MRNA", "Moderna Inc."),
    ("ANSS", "ANSYS Inc."), ("GEHC", "GE HealthCare Technologies Inc."),
    ("ILMN", "Illumina Inc."), ("SMCI", "Super Micro Computer Inc."),
    ("CDW", "CDW Corp."), ("TTWO", "Take-Two Interactive Software Inc."),
    ("ARM", "Arm Holdings plc"), ("DASH", "DoorDash Inc."),
    ("DDOG", "Datadog Inc."), ("AXON", "Axon Enterprise Inc."),
    ("ROP", "Roper Technologies Inc."), ("CSGP", "CoStar Group Inc."),
    ("CHTR", "Charter Communications Inc."), ("AZN", "AstraZeneca plc"),
    ("FANG", "Diamondback Energy Inc."), ("CEG", "Constellation Energy Corp."),
    ("EXC", "Exelon Corp."), ("WBD", "Warner Bros. Discovery Inc."),
    ("GFS", "GlobalFoundries Inc."), ("ALGN", "Align Technology Inc."),
    ("SIRI", "Sirius XM Holdings Inc."), ("PYPL", "PayPal Holdings Inc."),
    ("INTC", "Intel Corp."), ("PDD", "PDD Holdings Inc."),
    ("KHC", "Kraft Heinz Co."), ("BIDU", "Baidu Inc."),
    ("JD", "JD.com Inc."), ("LULU", "Lululemon Athletica Inc."),
    ("EBAY", "eBay Inc."), ("CMCSA", "Comcast Corp."),
]

SP_100 = [
    ("AAPL", "Apple Inc."), ("ABBV", "AbbVie Inc."), ("ABT", "Abbott Laboratories"),
    ("ACN", "Accenture plc"), ("AIG", "American International Group Inc."),
    ("ALL", "Allstate Corp."), ("AMGN", "Amgen Inc."), ("AMT", "American Tower Corp."),
    ("AMZN", "Amazon.com Inc."), ("AXP", "American Express Co."),
    ("BA", "Boeing Co."), ("BAC", "Bank of America Corp."),
    ("BK", "Bank of New York Mellon Corp."), ("BKNG", "Booking Holdings Inc."),
    ("BLK", "BlackRock Inc."), ("BMY", "Bristol-Myers Squibb Co."),
    ("BRK-B", "Berkshire Hathaway Inc."), ("C", "Citigroup Inc."),
    ("CAT", "Caterpillar Inc."), ("CHTR", "Charter Communications Inc."),
    ("CL", "Colgate-Palmolive Co."), ("CMCSA", "Comcast Corp."),
    ("COF", "Capital One Financial Corp."), ("COP", "ConocoPhillips"),
    ("COST", "Costco Wholesale Corp."), ("CRM", "Salesforce Inc."),
    ("CSCO", "Cisco Systems Inc."), ("CVS", "CVS Health Corp."),
    ("CVX", "Chevron Corp."), ("D", "Dominion Energy Inc."),
    ("DHR", "Danaher Corp."), ("DIS", "Walt Disney Co."),
    ("DUK", "Duke Energy Corp."), ("EMR", "Emerson Electric Co."),
    ("EXC", "Exelon Corp."), ("F", "Ford Motor Co."),
    ("FDX", "FedEx Corp."), ("GD", "General Dynamics Corp."),
    ("GE", "GE Aerospace"), ("GILD", "Gilead Sciences Inc."),
    ("GM", "General Motors Co."), ("GOOG", "Alphabet Inc."),
    ("GS", "Goldman Sachs Group Inc."), ("HD", "Home Depot Inc."),
    ("HON", "Honeywell International Inc."), ("IBM", "IBM Corp."),
    ("INTC", "Intel Corp."), ("JNJ", "Johnson & Johnson"),
    ("JPM", "JPMorgan Chase & Co."), ("KHC", "Kraft Heinz Co."),
    ("KO", "Coca-Cola Co."), ("LIN", "Linde plc"),
    ("LLY", "Eli Lilly and Co."), ("LMT", "Lockheed Martin Corp."),
    ("LOW", "Lowe's Companies Inc."), ("MA", "Mastercard Inc."),
    ("MCD", "McDonald's Corp."), ("MDLZ", "Mondelez International Inc."),
    ("MDT", "Medtronic plc"), ("MET", "MetLife Inc."),
    ("MMM", "3M Co."), ("MO", "Altria Group Inc."),
    ("MRK", "Merck & Co. Inc."), ("MS", "Morgan Stanley"),
    ("MSFT", "Microsoft Corp."), ("NEE", "NextEra Energy Inc."),
    ("NFLX", "Netflix Inc."), ("NKE", "Nike Inc."),
    ("NVDA", "NVIDIA Corp."), ("ORCL", "Oracle Corp."),
    ("OXY", "Occidental Petroleum Corp."), ("PEP", "PepsiCo Inc."),
    ("PFE", "Pfizer Inc."), ("PG", "Procter & Gamble Co."),
    ("PM", "Philip Morris International Inc."), ("PYPL", "PayPal Holdings Inc."),
    ("QCOM", "Qualcomm Inc."), ("RTX", "RTX Corp."),
    ("SBUX", "Starbucks Corp."), ("SO", "Southern Co."),
    ("SPG", "Simon Property Group Inc."), ("T", "AT&T Inc."),
    ("TGT", "Target Corp."), ("TMO", "Thermo Fisher Scientific Inc."),
    ("TSLA", "Tesla Inc."), ("TXN", "Texas Instruments Inc."),
    ("UNH", "UnitedHealth Group Inc."), ("UNP", "Union Pacific Corp."),
    ("UPS", "United Parcel Service Inc."), ("USB", "U.S. Bancorp"),
    ("V", "Visa Inc."), ("VZ", "Verizon Communications Inc."),
    ("WBA", "Walgreens Boots Alliance Inc."), ("WFC", "Wells Fargo & Co."),
    ("WMT", "Walmart Inc."), ("XOM", "Exxon Mobil Corp."),
    ("AVGO", "Broadcom Inc."), ("NOW", "ServiceNow Inc."),
    ("INTU", "Intuit Inc."), ("AMD", "Advanced Micro Devices Inc."),
]

NIFTY_100 = [
    ("RELIANCE.NS", "Reliance Industries Ltd."), ("TCS.NS", "Tata Consultancy Services"),
    ("HDFCBANK.NS", "HDFC Bank Ltd."), ("BHARTIARTL.NS", "Bharti Airtel Ltd."),
    ("ICICIBANK.NS", "ICICI Bank Ltd."), ("INFY.NS", "Infosys Ltd."),
    ("SBIN.NS", "State Bank of India"), ("HINDUNILVR.NS", "Hindustan Unilever Ltd."),
    ("ITC.NS", "ITC Ltd."), ("LT.NS", "Larsen & Toubro Ltd."),
    ("BAJFINANCE.NS", "Bajaj Finance Ltd."), ("HCLTECH.NS", "HCL Technologies Ltd."),
    ("SUNPHARMA.NS", "Sun Pharmaceutical Industries Ltd."),
    ("MARUTI.NS", "Maruti Suzuki India Ltd."), ("NTPC.NS", "NTPC Ltd."),
    ("ONGC.NS", "Oil & Natural Gas Corp. Ltd."), ("TITAN.NS", "Titan Company Ltd."),
    ("ADANIENT.NS", "Adani Enterprises Ltd."), ("KOTAKBANK.NS", "Kotak Mahindra Bank Ltd."),
    ("POWERGRID.NS", "Power Grid Corp. of India"), ("AXISBANK.NS", "Axis Bank Ltd."),
    ("WIPRO.NS", "Wipro Ltd."), ("ULTRACEMCO.NS", "UltraTech Cement Ltd."),
    ("BAJAJFINSV.NS", "Bajaj Finserv Ltd."), ("NESTLEIND.NS", "Nestle India Ltd."),
    ("M&M.NS", "Mahindra & Mahindra Ltd."), ("JSWSTEEL.NS", "JSW Steel Ltd."),
    ("ASIANPAINT.NS", "Asian Paints Ltd."), ("TATAMOTORS.NS", "Tata Motors Ltd."),
    ("COALINDIA.NS", "Coal India Ltd."), ("TATASTEEL.NS", "Tata Steel Ltd."),
    ("ADANIPORTS.NS", "Adani Ports & SEZ Ltd."), ("INDUSINDBK.NS", "IndusInd Bank Ltd."),
    ("BRITANNIA.NS", "Britannia Industries Ltd."), ("CIPLA.NS", "Cipla Ltd."),
    ("DRREDDY.NS", "Dr. Reddy's Laboratories Ltd."), ("EICHERMOT.NS", "Eicher Motors Ltd."),
    ("BPCL.NS", "Bharat Petroleum Corp. Ltd."), ("HEROMOTOCO.NS", "Hero MotoCorp Ltd."),
    ("HINDALCO.NS", "Hindalco Industries Ltd."), ("DIVISLAB.NS", "Divi's Laboratories Ltd."),
    ("GRASIM.NS", "Grasim Industries Ltd."), ("TECHM.NS", "Tech Mahindra Ltd."),
    ("SBILIFE.NS", "SBI Life Insurance Co. Ltd."), ("HDFCLIFE.NS", "HDFC Life Insurance Co. Ltd."),
    ("TATACONSUM.NS", "Tata Consumer Products Ltd."), ("BAJAJ-AUTO.NS", "Bajaj Auto Ltd."),
    ("APOLLOHOSP.NS", "Apollo Hospitals Enterprise Ltd."), ("SHRIRAMFIN.NS", "Shriram Finance Ltd."),
    ("LTIM.NS", "LTIMindtree Ltd."), ("PIDILITIND.NS", "Pidilite Industries Ltd."),
    ("SIEMENS.NS", "Siemens Ltd."), ("HAVELLS.NS", "Havells India Ltd."),
    ("DABUR.NS", "Dabur India Ltd."), ("MARICO.NS", "Marico Ltd."),
    ("COLPAL.NS", "Colgate-Palmolive India Ltd."), ("BERGEPAINT.NS", "Berger Paints India Ltd."),
    ("GODREJCP.NS", "Godrej Consumer Products Ltd."), ("MUTHOOTFIN.NS", "Muthoot Finance Ltd."),
    ("TORNTPHARM.NS", "Torrent Pharmaceuticals Ltd."), ("AMBUJACEM.NS", "Ambuja Cements Ltd."),
    ("ACC.NS", "ACC Ltd."), ("BANKBARODA.NS", "Bank of Baroda"),
    ("PNB.NS", "Punjab National Bank"), ("CANBK.NS", "Canara Bank"),
    ("VEDL.NS", "Vedanta Ltd."), ("TATAPOWER.NS", "Tata Power Co. Ltd."),
    ("DLF.NS", "DLF Ltd."), ("IRCTC.NS", "Indian Railway Catering & Tourism Corp."),
    ("ZOMATO.NS", "Zomato Ltd."), ("NYKAA.NS", "FSN E-Commerce Ventures Ltd."),
    ("PAYTM.NS", "One 97 Communications Ltd."), ("POLICYBZR.NS", "PB Fintech Ltd."),
    ("DMART.NS", "Avenue Supermarts Ltd."), ("TRENT.NS", "Trent Ltd."),
    ("CUMMINSIND.NS", "Cummins India Ltd."), ("ABB.NS", "ABB India Ltd."),
    ("BOSCHLTD.NS", "Bosch Ltd."), ("MPHASIS.NS", "Mphasis Ltd."),
    ("COFORGE.NS", "Coforge Ltd."), ("PERSISTENT.NS", "Persistent Systems Ltd."),
    ("INDUSTOWER.NS", "Indus Towers Ltd."), ("GAIL.NS", "GAIL India Ltd."),
    ("SAIL.NS", "Steel Authority of India Ltd."), ("NHPC.NS", "NHPC Ltd."),
    ("RECLTD.NS", "REC Ltd."), ("PFC.NS", "Power Finance Corp. Ltd."),
    ("IRFC.NS", "Indian Railway Finance Corp. Ltd."), ("HAL.NS", "Hindustan Aeronautics Ltd."),
    ("BEL.NS", "Bharat Electronics Ltd."), ("RVNL.NS", "Rail Vikas Nigam Ltd."),
    ("MFSL.NS", "Max Financial Services Ltd."), ("OBEROIRLTY.NS", "Oberoi Realty Ltd."),
    ("LODHA.NS", "Macrotech Developers Ltd."), ("MAXHEALTH.NS", "Max Healthcare Institute Ltd."),
    ("CHOLAFIN.NS", "Cholamandalam Investment & Finance Co."),
]

UNIVERSE_MAP = {
    "NASDAQ 100": NASDAQ_100,
    "S&P 100": SP_100,
    "NIFTY 100": NIFTY_100,
}
